# ========================
# Perfil: PROD (Oracle — TB_USER_GS, TB_PLANTACOES_GS, TB_SAFRA_GS, TB_INSUMO_GS, TB_RELATORIO_GS, TB_LOG_ERRO_GS)
# ========================
spring.datasource.url=oracle.fiap.com.br
spring.datasource.username=rm564002
spring.datasource.password=190905
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# validate: o Hibernate NÃO cria nem altera tabelas — o DDL já foi executado no Oracle
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.h2.console.enabled=false
