# ========================
# AgroVision - Configurações
# ========================
spring.application.name=agrovision
spring.profiles.active=dev

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Springdoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
jwt.secret=agrovision-fiap-global-solution-2026-chave-secreta-256bits
jwt.expiration=86400000
