# ========================
# Perfil: DEV (H2 in-memory)
# ========================
spring.datasource.url=jdbc:h2:mem:agrovision_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# create-drop recria as tabelas a cada inicialização (ideal para dev/testes)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
